### ISSUE TITLE
Sass.development missing

### ISSUE THREAD

**Issue by tjmaxwell** [pixelcabin/ziplines#2]
Hello,

Thanks for this!  I just created my first project with ziplines, but I'm having an issue when I add css, scss, css.liquid, or scss.liquid files to the scss folder.  In my terminal, this error occurs:

> > File "src/scss/apps.css.liquid" added.
> > Running "sass:development" (sass) task
> > Verifying property sass.development exists in config...ERROR
> > Unable to process task.
> > Warning: Required config property "sass.development" missing. Use --force to continue.

Aborted due to warnings.

Can you please help me resolve this?

Thanks,
Tim

**Comment by michaelrshannon** [comment]
Hi @tjmaxwell - thanks for the report! The first problem could be that the `src/scss` folder is only set up to handle `.scss` files - if you have an `css.liquid` file that you want to include, it will need to go within the `shop/assets` folder, as liquid won't be correctly processed by the sass compiler that monitors the `src/scss` folder.

That may resolve the issue, but if not, could you let me know which version of Node you're using (`node -v`), and which OS you're working on?

**Comment by michaelrshannon** [comment]
Marking as resolved for now.

**Comment by Jorybraun** [comment]
I'm having this same issue right out of the box after creating my first store. I can't seem to find an application.css or scss in my directory either.

**Comment by Jorybraun** [comment]
my node version is 5.6.0
